### PR TITLE
Windows

### PR DESCRIPTION
**Pull request by looooo**
- add script from sgrogan: https://forum.freecadweb.org/viewtopic.php?f=42&t=44157
- travis: enable windows

more iterations necessary!!!

### CODE REVIEW

**Comment by looooo** [comment]
seems like travis is not triggered anymore...

**Comment by triplus** [comment]
After the last change Travis could not parse .travis.yml anymore. Likely some issue with the file structure.

**Comment by triplus** [comment]
Should be back now.

**Comment by looooo** [comment]
thanks for fixing it @triplus

**Comment by looooo** [comment]
```
2020-03-18 15:42:42 (29.5 MB/s) - 'conda.exe' saved [13488123/13488123]
/c/Users/travis/.travis/functions: line 109: conda.exe: command not found
/c/Users/travis/.travis/functions: line 109: call: command not found
```

**Comment by looooo** [comment]
great! Are you able to debug this kind of issues locally? I really feel lost with this bash, yml mix...

**Comment by triplus** [comment]
What helped the most is around a month back i was tackling the FreeCAD Travis Windows build issues and i could reuse that knowledge here.

P.S. I will tackle deployment around Monday. There are some Windows specifics involved and i need to check that first more in-depth.

**Pull request merged**
