### PR TITLE
initial scripts to produce .app from conda-packages on osx

### PR DESCRIPTION
**Pull request by looooo**
not yet working...

TODO:
- try the script locally
- setup travis to create the .app

### CODE REVIEW

**Comment by looooo** [comment]
@triplus is this the wrong place to host the osx .app .

**Comment by bblacey** [comment]
If Conda becomes the cross-platform package manager of choice, I think we have several options.

1.  Maintain separate, platform-specific repos such as FreeCAD-AppImage, FreeCAD-Windows, and FreeCAD-macOS each with a .travis config whose sole purpose is to perform a Conda install and then package for the specific platform (yes, Travis supports Windows now too or we could use Azure pipelines or AppVeyor) and finally deploy to GitHub.
2. Maintain a single "FreeCAD-Conda-Apps repo (or some such name) that includes a single .travis.yml config file that installs using Conda and packages for each separate platform.  If we lean towards option 2, then we could just add the Conda packaging to the current FreeCAD/FreeCAD/.travis.yml

It all depends on how much or how little, platform-specific code is required beyond the Conda install to package each.  In theory the install and deploy should be the same so it really comes down to the platform-specific artifact packaging.

**Comment by triplus** [comment]
Hi @looooo 

I am fine with all suggestions. Whatever makes the most sense, and turns out to be the most practical and straightforward to maintain solution for us, has my vote. Therefore first thing i guess is to make it work. That is to produce a working macOS build, based on Conda packages, and for it to be deployed on GitHub releases page successfully. I am guessing the whole procedure shouldn't take much more resources, compared to creating AppImage. Therefore just do it.

As for the future. Suggestions from @bblacey should be evaluated more in-depth. That is if it makes sense to have one Travis instance doing AppImage, macOS and potentially Windows Conda based builds, or if it would make more sense to split them up. If you feel it would make more sense to split them up right from the beginning, hopefully @bblacey will take care of that. As he has done that for the AppImage purposes.

For Windows builds (based on Conda packages). Best if we ask @sgrogan, on how he feels about that. I am guessing he could be interested in automating the procedure in such way, but best to ask first.

**Comment by bblacey** [comment]
I'm a fan of the heroic work that @looooo has been doing on Conda and I think it holds promise as a cross-platform app packaging solution for FreeCAD (IMHO).  We have very few macOS resources and I am currently working on "fixing" the Homebrew macOS builds by implementing an auto-bottling solution the FreeCAD formulae that we rely upon to reduce the macOS maintenance effort because it can be like chasing a stone down a hill as dependencies (e.g. Qt) evolve.  @peterlama has been a trooper on macOS, but @ianreese is on Linux now so we always have to scrape resources together to keep macOS on Homebrew moving forward as dependencies evolve.  If we had a singular unified way to build FreeCAD against a broad set of changing dependencies, then we should be able to maintain cadence across all platforms with less effort and @looooo's Conda path might be that solution.

Once we fix the Homebrew builds (@peterlama and I), I'de be happy to help @looooo with the Conda for macOS effort regardless of the path we choose (singular vs. separate) and subject the macOS packaging to a Homebrew/Conda bake-off to vet the best long-term solution.

@peterlama - it would be good to get your view on the relative merits of Homebrew vs. Conda for macOS...

**Comment by triplus** [comment]
@bblacey 

I feel that your work and the work macOS team has been doing is still much needed and appreciated. As packaging stable releases, continuous integration, macOS packages made available after each commit ... Conda effort can't replace all that, at least not for now. In addition if macOS packaging team wouldn't enable all the things it did in the past, on the Travis front, we likely wouldn't have this conversation here today. Maybe daily AppImage offering wouldn't be provided.

I do see much value in achieving weekly and automated Conda based AppImage, macOS and potentially Windows builds. As i have seen having both Conda/PPA based AppImage offering complemented nicely. Things like having the Py2/Py3/Qt4/Qt5 matrix covered on Linux. Sometimes other things take priority and then it is nice to have 2 distribution channels you can rely on. If one channel is temporarily unavailable. In addition sometimes things change, that we don't have much say in. In regards to packaging for one channel. It usually takes time to sort things out. During that time the other channel likely doesn't experience such issues.

What i can say is macOS users are currently longing for having daily macOS builds again, and that i guess says it all.

**Comment by looooo** [comment]
this should work now locally (creating a dmg file). Now we need to figure out how to proceed:

1. can we run a second travis instance with osx?
2. upload to the freecad-repo. I don't know how this works. @bblacey can you give some insights?

**Comment by sgrogan** [comment]
Hey @looooo 
I will merge this, we must get you permissions!

I like @bblacey #2 above.

**Comment by looooo** [comment]
yes I think this is also the better option. Still we need to figure out how to run the different systems on one ci.

**Comment by core-code** [comment]
*please* don't leave the 	`<key>CFBundleIdentifier</key>` empty. every Mac app is supposed to have one and standard functionality like Caching and native preferences is just broken if its missing

**Pull request merged**
