### PR TITLE
[WIP] add env variables

### PR DESCRIPTION
**Pull request by looooo**

### CODE REVIEW

**Comment by sgrogan** [comment]
merged

**Comment by looooo** [comment]
not yet : ). But wait maybe there is more to come...

**Comment by looooo** [comment]
- [ ] TODO: Appimage naming not good with new script.

**Comment by looooo** [comment]
@bblacey if you see this, maybe you can give some hints how to:
1. enable osx in travis
2. upload the dmg

These two points are still missing to enable upload of the weekly builds for osx.

**Comment by looooo** [comment]
@triplus this will change nearly all libs included in the appimage. Do we have to reset the zsync stuff?

**Comment by triplus** [comment]
> @triplus this will change nearly all libs included in the appimage. Do we have to reset the zsync stuff?

No, nothing needs to get reset.

**Comment by looooo** [comment]
Ah good. I was a little bit under pressure, that's why I merged.
Is it somehow possible to see if the builds are uploaded? I would like to test if the release should be based on py3.6 or py3.7... but somehow there are no 0.19pre builds available at the release page.

Also I think we are still uploading to 0.18pre instead of 0.19pre.

**Pull request merged**
