### PR TITLE
osx: add ssl_cert_file variable

### PR DESCRIPTION
**Pull request by looooo**
@triplus I didn't push directly as I saw you are working on the appimage. Maybe you have some time to merge this one. I have tested it localy and it should fix the addon-manager problem on osx:
https://forum.freecadweb.org/viewtopic.php?f=3&t=42825

### CODE REVIEW

**Comment by triplus** [comment]
Done.

**Comment by looooo** [comment]
thx

**Comment by probonopd** [comment]
Interesting. This might potentially be useful for other AppImages as well. Why did you use `SSL_CERT_FILE` rather than `SSL_CERT_DIR`?

**Comment by triplus** [comment]
It is actually used in the AppImage already:

https://github.com/FreeCAD/FreeCAD-AppImage/blob/master/conda/linux_dev/AppDir/AppRun

Therefore i can confirm it is useful for AppImage purposes. At that time i tested different things and this is the one that work. I did a quick tests and it doesn't look like SSL_CERT_DIR is working. I tested on my local machine (extracted AppImage).

**Pull request merged**
